---
kind: pipeline
type: docker
name: default

steps:
  - name: bootstrap
    image: node:dubnium-jessie
    when:
      event: push
    commands:
      - npm ci
      - npm test
      - npm run build
  - name: publish
    image: plugins/npm
    when:
      branch:
      - master
    settings:
      username: sugarandmagic
      password:
        from_secret: npm_password
      email: carrie@carriebeesley.com
