---
kind: pipeline
type: docker
name: default

steps:
  - name: npm-login
    image: node:dubnium-jessie
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
  - name: bootstrap
    image: node:dubnium-jessie
    when:
      event: push
    commands:
      - npm ci
      - npm test
      - npm run build
  - name: test
    image: node:dubnium-jessie
    when:
      event: push
    commands:
      - npm test
  - name: publish
    image: node:dubnium-jessie
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    when:
      branch:
      - master
    commands:
      - npm whoami
      - npm run release
